vpc_name                               = "aqua-assignment-vpc"
vpc_cidr                               = "10.0.0.0/16"
vpc_azs                                = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]
vpc_private_subnets                    = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
vpc_public_subnets                     = ["10.0.11.0/24", "10.0.12.0/24", "10.0.13.0/24"]
vpc_manage_default_route_table         = true
vpc_enable_nat_gateway                 = true
vpc_single_nat_gateway                 = true
vpc_enable_dns_hostnames               = true
vpc_enable_dns_support                 = true